---
- name: "configuration play."
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "upgrade packages"
      become: yes
      apt:
        upgrade: yes
      register: result
      until: result is success
      retries: 5
      delay: 5
      ignore_errors: yes

    - name: General | Instalacion de paquetes requeridos.
      apt:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
        force_apt_get: yes
      become: yes
      vars:
        packages:
          - python3
          - python3-pip
          - tar
          - nodejs
          - npm

    - name: "install pm2"
      become: yes
      npm:
        name: pm2
        global: yes
        production: yes
        state: present

  roles:
    - deploy
