---
- name: "configuration play."
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "install python"
      become: yes
      apt:
        name: ["python3", "python3-pip"]
        state: latest
        update_cache: yes

    - name: "update apt packages."
      apt:
        update_cache: yes
      become: yes

    - name: "upgrade packages"
      become: yes
      apt:
        upgrade: yes

    - name: "install dependencies."
      become: yes
      apt:
        name: ["nodejs", "npm"]
        state: latest
        update_cache: yes

    - name: "install pm2"
      become: yes
      npm:
        name: pm2
        global: yes
        production: yes
        state: present

  roles:
    - deploy
