- name: Copy backend files
  copy:
    src: /root/project/artifact.tar.gz
    dest: artifact.tar.gz

- shell: tar -xzvf artifact.tar.gz -C /tmp
  become: true

- name: "Install npm dependencies."
  npm:
    path: /tmp
    state: present
  become: true

- name: "Stop the running app (if any)."
  command: pm2 stop default || true
  ignore_errors: true
  become: true

- name: "Start the app with pm2."
  command: pm2 start npm -- start
  args:
    chdir: /tmp
  become: true
