- name: Copy backend files
  copy:
    src: /root/project/artifact.tar.gz
    dest: artifact.tar.gz

- name: "extract zipped artifact."
  ansible.builtin.unarchive:
    src: artifact.tar.gz
    dest: /tmp
    remote_src: yes
    extra_opts:
      - "-zxf"
      - "--strip-components=1"
  become: true

- name: "Install npm dependencies."
  npm:
    path: /tmp
    state: present
  become: true

- name: "Stop the app with pm2."
  command: pm2 stop default
  become: true

- name: "Start the app with pm2."
  command: pm2 start npm -- start
  args:
    chdir: /tmp
  become: true
