---
- name: "install python"
  become: yes
  apt:
    name: ["python3", "python3-pip"]
    state: latest
    update_cache: yes

- name: "update apt packages."
  apt:
    update_cache: yes
  become: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
