- name: "list files"
  shell: "ls -al"
  become: true

- name: "extract zipped artifact."
  unarchive:
    src: artifact.tar.gz
    dest: /tmp
    remote_src: yes

- name: "Install npm dependencies."
  npm:
    path: /tmp
    state: present
  become: true

- name: "Stop the app with pm2."
  command: pm2 stop default
  become: true

- name: "Start the app with pm2."
  command: pm2 start npm -- start
  args:
    chdir: /tmp
  become: true
